language: c

install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq lcov curl valgrind

matrix:
  include:
  - compiler: gcc
  - compiler: clang

script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
  - make
  - valgrind --error-exitcode=1 ./tests
